import { formatNumber, formatCurrency } from './utils'

export interface CsvColumn {
  key: string
  label: string
  format?: (value: any, row: any) => string | number
}

/**
 * Escapes and encodes a string for CSV compatibility (RFC 4180).
 */
function escapeCsvValue(val: any): string {
  if (val === null || val === undefined) return ''
  const str = String(val)
  if (str.includes(',') || str.includes('"') || str.includes('\n') || str.includes('\r')) {
    return `"${str.replace(/"/g, '""')}"`
  }
  return str
}

/**
 * Exports data to a downloaded CSV file.
 */
export function exportToCsv(filename: string, columns: CsvColumn[], data: any[]): void {
  const headerRow = columns.map((col) => escapeCsvValue(col.label)).join(',')
  const dataRows = data.map((row) =>
    columns
      .map((col) => {
        const val = col.format ? col.format(row[col.key], row) : row[col.key]
        return escapeCsvValue(val)
      })
      .join(',')
  )

  const csvContent = [headerRow, ...dataRows].join('\r\n')
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)

  const link = document.createElement('a')
  link.href = url
  link.download = filename.endsWith('.csv') ? filename : `${filename}.csv`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Exports data to a downloaded JSON file.
 */
export function exportToJson(filename: string, data: any): void {
  const jsonContent = JSON.stringify(data, null, 2)
  const blob = new Blob([jsonContent], { type: 'application/json;charset=utf-8;' })
  const url = URL.createObjectURL(blob)

  const link = document.createElement('a')
  link.href = url
  link.download = filename.endsWith('.json') ? filename : `${filename}.json`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Exports data to a downloaded Markdown file.
 */
export function exportToMarkdown(filename: string, title: string, columns: CsvColumn[], data: any[]): void {
  let md = `# ${title}\n\n`
  md += `*Exported on ${new Date().toLocaleString()}*\n\n`
  md += `| ${columns.map((c) => c.label).join(' | ')} |\n`
  md += `| ${columns.map(() => '---').join(' | ')} |\n`

  for (const row of data) {
    const cells = columns.map((col) => {
      const val = col.format ? col.format(row[col.key], row) : row[col.key]
      return String(val ?? '').replace(/\|/g, '\\|')
    })
    md += `| ${cells.join(' | ')} |\n`
  }

  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename.endsWith('.md') ? filename : `${filename}.md`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Copies a markdown table summary to clipboard.
 */
export async function copyMarkdownTable(
  title: string,
  metadata: Record<string, string | number>,
  headers: string[],
  rows: (string | number)[][]
): Promise<boolean> {
  const lines: string[] = []
  lines.push(`### ${title}`)
  lines.push('')

  if (Object.keys(metadata).length > 0) {
    for (const [key, value] of Object.entries(metadata)) {
      lines.push(`- **${key}**: ${value}`)
    }
    lines.push('')
  }

  // Header
  lines.push(`| ${headers.join(' | ')} |`)
  lines.push(`| ${headers.map(() => '---').join(' | ')} |`)

  // Rows
  for (const row of rows) {
    lines.push(`| ${row.map((cell) => String(cell).replace(/\|/g, '\\|')).join(' | ')} |`)
  }

  lines.push('')
  lines.push(`*Generated by Token Tracker on ${new Date().toLocaleString()}*`)

  try {
    await navigator.clipboard.writeText(lines.join('\n'))
    return true
  } catch (err) {
    console.error('Failed to copy markdown:', err)
    return false
  }
}

export interface ReportData {
  startDate: number
  endDate: number
  totals: {
    inputTokens: number
    outputTokens: number
    cacheReadTokens: number
    cacheCreationTokens: number
    totalTokens: number
    totalCost: number
    totalTurns: number
  }
  projectBreakdown: Array<{
    id: string
    name: string
    toolSource: string
    totalTokens: number
    totalCost: number
    sessionsCount: number
    turnCount: number
  }>
  toolBreakdown: Array<{
    toolSource: string
    totalTokens: number
    totalCost: number
    turnCount: number
  }>
  modelBreakdown: Array<{
    model: string
    totalTokens: number
    totalCost: number
    turnCount: number
  }>
}

/**
 * Generates and downloads a standalone, print-ready HTML expense and telemetry report.
 */
export function generatePrintableHtmlReport(
  report: ReportData,
  branding?: { company?: string; author?: string; title?: string }
): void {
  const startStr = report.startDate > 0 ? new Date(report.startDate).toLocaleDateString() : 'Beginning of records'
  const endStr = new Date(report.endDate).toLocaleDateString()
  const generatedAt = new Date().toLocaleString()
  const reportTitle = branding?.title?.trim() || 'Token Tracker — AI Telemetry & Expense Report'
  const brandingMeta = [branding?.author?.trim(), branding?.company?.trim()].filter(Boolean).join(' · ')

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${reportTitle} — ${startStr} to ${endStr}</title>
  <style>
    :root {
      --bg: #ffffff;
      --text: #111111;
      --muted: #666666;
      --border: #e5e5e5;
      --card-bg: #f9f9f9;
      --emerald: #059669;
    }
    @media (prefers-color-scheme: dark) {
      :root {
        --bg: #09090b;
        --text: #ededed;
        --muted: #a1a1aa;
        --border: #27272a;
        --card-bg: #18181b;
        --emerald: #10b981;
      }
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      background: var(--bg);
      color: var(--text);
      line-height: 1.5;
      margin: 0;
      padding: 32px;
    }
    .container {
      max-width: 900px;
      margin: 0 auto;
    }
    header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      border-bottom: 2px solid var(--border);
      padding-bottom: 20px;
      margin-bottom: 24px;
    }
    h1 {
      font-size: 22px;
      font-weight: 700;
      margin: 0 0 6px 0;
      letter-spacing: -0.02em;
    }
    .meta {
      color: var(--muted);
      font-size: 13px;
    }
    .branding-sub {
      color: var(--emerald);
      font-size: 12px;
      font-weight: 600;
      margin-top: 4px;
    }
    .btn {
      background: #000000;
      color: #ffffff;
      border: 1px solid #333333;
      padding: 8px 16px;
      font-size: 12px;
      font-weight: 500;
      border-radius: 6px;
      cursor: pointer;
    }
    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      gap: 16px;
      margin-bottom: 32px;
    }
    .card {
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 16px;
    }
    .card-label {
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: var(--muted);
      margin-bottom: 4px;
    }
    .card-value {
      font-size: 20px;
      font-weight: 600;
      font-family: monospace;
    }
    .cost-val {
      color: var(--emerald);
    }
    h2 {
      font-size: 16px;
      font-weight: 600;
      margin: 28px 0 12px 0;
      letter-spacing: -0.01em;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 13px;
      margin-bottom: 28px;
    }
    th, td {
      padding: 10px 12px;
      text-align: left;
      border-bottom: 1px solid var(--border);
    }
    th {
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      background: rgba(0, 0, 0, 0.02);
      color: var(--muted);
    }
    td.num, th.num {
      text-align: right;
      font-family: monospace;
    }
    footer {
      border-top: 1px solid var(--border);
      padding-top: 16px;
      margin-top: 40px;
      font-size: 11px;
      color: var(--muted);
      display: flex;
      justify-content: space-between;
    }
    @media print {
      body {
        background: #ffffff !important;
        color: #000000 !important;
        padding: 0;
      }
      .no-print {
        display: none !important;
      }
      .card {
        background: #ffffff !important;
        border: 1px solid #cccccc !important;
      }
      th {
        background: #f0f0f0 !important;
        color: #333333 !important;
      }
      td, th {
        border-bottom: 1px solid #dddddd !important;
      }
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <div>
        <h1>${reportTitle}</h1>
        <div class="meta">Period: <strong>${startStr}</strong> — <strong>${endStr}</strong></div>
        ${brandingMeta ? `<div class="branding-sub">Prepared by ${brandingMeta}</div>` : ''}
      </div>
      <div class="no-print">
        <button class="btn" onclick="window.print()">Print / Save as PDF</button>
      </div>
    </header>

    <div class="grid">
      <div class="card">
        <div class="card-label">Total Spend</div>
        <div class="card-value cost-val">${formatCurrency(report.totals.totalCost)}</div>
      </div>
      <div class="card">
        <div class="card-label">Total Tokens</div>
        <div class="card-value">${formatNumber(report.totals.totalTokens)}</div>
      </div>
      <div class="card">
        <div class="card-label">Input Tokens</div>
        <div class="card-value">${formatNumber(report.totals.inputTokens)}</div>
      </div>
      <div class="card">
        <div class="card-label">Output Tokens</div>
        <div class="card-value">${formatNumber(report.totals.outputTokens)}</div>
      </div>
      <div class="card">
        <div class="card-label">Cached Tokens</div>
        <div class="card-value">${formatNumber(report.totals.cacheReadTokens + report.totals.cacheCreationTokens)}</div>
      </div>
      <div class="card">
        <div class="card-label">Turn Count</div>
        <div class="card-value">${formatNumber(report.totals.totalTurns)}</div>
      </div>
    </div>

    <h2>Breakdown by Project</h2>
    <table>
      <thead>
        <tr>
          <th>Project</th>
          <th>Source</th>
          <th class="num">Sessions</th>
          <th class="num">Turns</th>
          <th class="num">Total Tokens</th>
          <th class="num">Cost (USD)</th>
        </tr>
      </thead>
      <tbody>
        ${report.projectBreakdown
          .map(
            (p) => `<tr>
          <td><strong>${p.name}</strong></td>
          <td>${p.toolSource}</td>
          <td class="num">${p.sessionsCount}</td>
          <td class="num">${p.turnCount}</td>
          <td class="num">${formatNumber(p.totalTokens)}</td>
          <td class="num"><strong>${formatCurrency(p.totalCost)}</strong></td>
        </tr>`
          )
          .join('')}
      </tbody>
    </table>

    <h2>Breakdown by Tool / Source</h2>
    <table>
      <thead>
        <tr>
          <th>Tool Source</th>
          <th class="num">Turns</th>
          <th class="num">Total Tokens</th>
          <th class="num">Cost (USD)</th>
        </tr>
      </thead>
      <tbody>
        ${report.toolBreakdown
          .map(
            (t) => `<tr>
          <td><strong>${t.toolSource}</strong></td>
          <td class="num">${t.turnCount}</td>
          <td class="num">${formatNumber(t.totalTokens)}</td>
          <td class="num"><strong>${formatCurrency(t.totalCost)}</strong></td>
        </tr>`
          )
          .join('')}
      </tbody>
    </table>

    <h2>Breakdown by Model</h2>
    <table>
      <thead>
        <tr>
          <th>Model</th>
          <th class="num">Turns</th>
          <th class="num">Total Tokens</th>
          <th class="num">Cost (USD)</th>
        </tr>
      </thead>
      <tbody>
        ${report.modelBreakdown
          .map(
            (m) => `<tr>
          <td><strong>${m.model}</strong></td>
          <td class="num">${m.turnCount}</td>
          <td class="num">${formatNumber(m.totalTokens)}</td>
          <td class="num"><strong>${formatCurrency(m.totalCost)}</strong></td>
        </tr>`
          )
          .join('')}
      </tbody>
    </table>

    <footer>
      <span>Generated by Token Tracker ${brandingMeta ? `(${brandingMeta})` : '(Exact Local Telemetry)'}</span>
      <span>${generatedAt}</span>
    </footer>
  </div>
</body>
</html>`

  const blob = new Blob([html], { type: 'text/html;charset=utf-8;' })
  const url = URL.createObjectURL(blob)

  const dateSlug = `${startStr.replace(/\//g, '-')}_to_${endStr.replace(/\//g, '-')}`
  const link = document.createElement('a')
  link.href = url
  link.download = `token-tracker-report-${dateSlug}.html`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
