import crypto from 'node:crypto'

export const SHARED_ACTIVATION_SECRET = 'TT_PRO_ACTIVATION_SECRET_KEY_2026_QOL_UNLOCKED'

export interface VerificationResult {
  valid: boolean
  reason?: 'invalid' | 'expired'
}

/**
 * Validates a self-verifying activation code generated by the Token Tracker website.
 * Format: base64(timestamp + ":" + HMAC-SHA256(timestamp, SHARED_SECRET))
 * Expiration: Valid if currentTime - timestamp <= 30 minutes.
 */
export function verifyActivationCode(
  rawCode: string,
  secret: string = SHARED_ACTIVATION_SECRET
): VerificationResult {
  try {
    if (!rawCode || typeof rawCode !== 'string') {
      return { valid: false, reason: 'invalid' }
    }

    const trimmed = rawCode.trim()
    const decoded = Buffer.from(trimmed, 'base64').toString('utf-8')
    const colonIdx = decoded.indexOf(':')
    if (colonIdx === -1) {
      return { valid: false, reason: 'invalid' }
    }

    const timestampStr = decoded.slice(0, colonIdx)
    const providedSig = decoded.slice(colonIdx + 1)

    const timestamp = parseInt(timestampStr, 10)
    if (isNaN(timestamp) || timestamp <= 0) {
      return { valid: false, reason: 'invalid' }
    }

    const now = Date.now()
    const thirtyMinutesMs = 30 * 60 * 1000

    // Reject if expired (older than 30 minutes) or suspiciously far in future (> 5 min clock skew)
    if (now - timestamp > thirtyMinutesMs || timestamp - now > 5 * 60 * 1000) {
      return { valid: false, reason: 'expired' }
    }

    // Recompute HMAC-SHA256(timestamp, secret)
    const hmac = crypto.createHmac('sha256', secret)
    hmac.update(timestampStr)
    const expectedSig = hmac.digest('hex')

    if (providedSig.length !== expectedSig.length) {
      return { valid: false, reason: 'invalid' }
    }

    const isValid = crypto.timingSafeEqual(
      Buffer.from(providedSig, 'hex'),
      Buffer.from(expectedSig, 'hex')
    )

    if (isValid) {
      return { valid: true }
    } else {
      return { valid: false, reason: 'invalid' }
    }
  } catch {
    return { valid: false, reason: 'invalid' }
  }
}
